import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { AuthProvider } from '../context/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// クライアントコンポーネントとしてAuthProviderをラップ
'use client';
const ClientAuthProvider = ({ children }) => {
  return <AuthProvider>{children}</AuthProvider>;
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ClientAuthProvider>
            {children}
          </ClientAuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}